apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sx3d
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-sx3d@sha256:b50988acc81458b69cbc6c75bbed9b8b20883914b57b65ed806fe9ff0500e56e
        name: my-nodejs
        resources: {}
status: {}
